# -*- coding: utf-8 -*-
"""cryptanalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6e2GTbflDtIn0elZgOrFejwa3cqyZZq
"""

def cryptanalysis():
  cipher_text=input('Enter the cipher text:')
  for k in range(26):
    plain_text=''
    for letter in cipher_text:
      c=ord(letter)-65
      e=(c-k)%26
      plain_text+=chr(e+65)
    print('With key = ',k,plain_text)
cryptanalysis()