# -*- coding: utf-8 -*-
"""stegano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lGmIyUvfkFb7GhRC2lw4elZYwyOgbp-
"""

from stegano import lsb

message = input("Enter Message You want to hide: ")
img_file_text = lsb.hide('/content/sample_data/dl.jpg', message)

saved = 'sec.png'
img_file_text.save(saved)
print("Saved Succesfully")

message = lsb.reveal(saved)
print('Reveal message: ',str(message))

pwd